### ISSUE TITLE
Failed to load assets in Sail

### ISSUE THREAD

**Issue by damms005** [laravel/dusk#1091]
### Dusk Version

8.0.0

### Laravel Version

10.48.2

### PHP Version

8.2.8

### PHPUnit Version

10.5.12

### Database Driver & Version

mysql  Ver 8.0.32 for Linux on x86_64 (MySQL Community Server - GPL)

### Description

Assets are not loaded when running Dusk tests.

```
test('homepage', function () {
    $student = addStudent();

    $this->browse(function (Browser $browser) use ($student) {
        $browser->visit(route('homepage'))
            ->loginAs($student->userModel->id)
            ->storeConsoleLog('error-log') // --> debug purposes
            ->assertSee('Something');
    });
});
```

## Console log output
```
[
    {
        "level": "SEVERE",
        "message": "http:\/\/tims.local\/build\/assets\/app-931911db.css - Failed to load resource: net::ERR_CONNECTION_REFUSED",
        "source": "network",
        "timestamp": 1710742000259
    },
    {
        "level": "SEVERE",
        "message": "http:\/\/tims.local\/new-frontend\/assets\/js\/jquery.min.js - Failed to load resource: net::ERR_CONNECTION_REFUSED",
        "source": "network",
        "timestamp": 1710742000259
    },
    {
        "level": "SEVERE",
        "message": "http:\/\/tims.local\/build\/assets\/main-f5d540ec.js - Failed to load resource: net::ERR_CONNECTION_REFUSED",
        "source": "network",
        "timestamp": 1710742000259
    },
    {
        "level": "SEVERE",
        "message": "http:\/\/tims.local\/build\/assets\/main-97df0a5b.js - Failed to load resource: net::ERR_CONNECTION_REFUSED",
        "source": "network",
        "timestamp": 1710742000259
    },
    {
        "level": "SEVERE",
        "message": "http:\/\/tims.local\/favicon-32x32.png - Failed to load resource: net::ERR_CONNECTION_REFUSED",
        "source": "network",
        "timestamp": 1710742000774
    },
    {
        "level": "SEVERE",
        "message": "http:\/\/tims.local\/favicon-16x16.png - Failed to load resource: net::ERR_CONNECTION_REFUSED",
        "source": "network",
        "timestamp": 1710742000774
    }
]
```

## docker-compose.yml
```
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: tims-laravel-sail-php8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            PHP_CLI_SERVER_WORKERS: 10
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - selenium
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    selenium:
      image: 'selenium/standalone-chrome'
      extra_hosts:
        - 'host.docker.internal:host-gateway'
      volumes:
          - '/dev/shm:/dev/shm'
      networks:
          - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
```

### Steps To Reproduce

- Setup a new Sail app
- Setup Dusk
- Write a test that accesses any page that requires assets to be loaded
- Log console errors using `->storeConsoleLog('...')`
- Run the Dusk test using `sail dusk`
- See connection refused errors as shown in the issue description above
