### ISSUE TITLE
Dusk on CircleCI dropdown element not visible

### ISSUE THREAD

**Issue by akash-dangal** [laravel/dusk#274]
I have problem with laravel dusk, the code below works when I test it in my locals , but CircleCI has error ` element not visible ` 
`->type('name', 'Test User') ` never works in CircleCI, however `->keys('input[name="name"]', 'Test User')` works so I replace all type with keys for text input .. Now I have another problem with ` ->select('country_id', '58')`  I have tried with so many selectors including (class, id , select , name etc ) nothing working and I am badly stuck here.
Any guidance would be much appreciated.

Below is a simple add user test with dusk..
```
 $browser->loginAs($user)
                    ->visit(route('user-add'))
                    ->keys('input[name="name"]', 'Test User')
                    ->keys('input[name="email"]', 'testuser@orguser.com')
                    ->select('country_id', '58')
                    ->select('language_id', '1')
                    ->attach('image', $image)
                    ->keys('input[name="phone"]', '602323232323')
                    ->press('Submit')
                    ->assertPathIs('/en-US/admin/user-listing')
                    ->assertSee('User added succesfully');
```
Is this problem related to my circle.yml ?? I need to add some more installers ?? 
```
machine:
  php:
    version: 7.1.0
  node:
    version: 6.1.0
  environment:
    DB_DATABASE: circle_test
    DB_USERNAME: root
    MAIL_DRIVER: log
    APP_ENV: local
database:
  override:
    # create the database
    - php artisan migrate --seed --verbose --no-interaction --env=testing
    - mysqldump --no-data circle_test
dependencies:
  pre:
    - sudo apt-get install libdbd-mysql-perl
test:
  pre:
# google chrome update
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update
    - sudo apt-get --only-upgrade install google-chrome-stable
    # laravel dusk setups
    - "./vendor/laravel/dusk/bin/chromedriver-linux":
        background: true
    - cp .env.dusk.circle .env
    - "php artisan serve":
        background: true
    - google-chrome --version
  post:
      - php artisan dusk

```
