### ISSUE TITLE
Problem running Laravel Dusk test in Travis

### ISSUE THREAD

**Issue by jaonoctus** [laravel/dusk#454]
I'm trying to get Travis to run the Dusk test, but I always get an error. The tests work well on my local environment, but when Travis run the Test I get an error like this: `NoSuchElementException: no such element: Unable to locate element:` ([see on travis](https://travis-ci.org/jaonoctus/exchange/builds/339265603))

> .travis.yml
```yml
sudo: required
language: php
dist: trusty

php:
   - 7.2

addons:
   chrome: stable

install:
   - cp .env.example .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php artisan serve &

script:
   - php artisan dusk
```
